version: '3.8'

services:
  gallery-dl:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./downloads:/downloads
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
